/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoLocXanhRouteImport } from './routes/bo-loc-xanh'
import { Route as CongTacVienRouteImport } from './routes/cong-tac-vien'
import { Route as DoiTacRouteImport } from './routes/doi-tac'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as AuthenticatedHoSoCuaToiRouteImport } from './routes/_authenticated/ho-so-cua-toi'
import { Route as AuthenticatedNopHoSoRouteImport } from './routes/_authenticated/nop-ho-so'
import { Route as AuthenticatedQuanTriRouteImport } from './routes/_authenticated/quan-tri'
import { Route as ChienDichIndexRouteImport } from './routes/chien-dich.index'
import { Route as ChienDichSlugRouteImport } from './routes/chien-dich.$slug'
import { Route as DongGopSlugRouteImport } from './routes/dong-gop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoLocXanhRoute = BoLocXanhRouteImport.update({
  id: '/bo-loc-xanh',
  path: '/bo-loc-xanh',
  getParentRoute: () => rootRouteImport,
} as any)
const CongTacVienRoute = CongTacVienRouteImport.update({
  id: '/cong-tac-vien',
  path: '/cong-tac-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const DoiTacRoute = DoiTacRouteImport.update({
  id: '/doi-tac',
  path: '/doi-tac',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHoSoCuaToiRoute = AuthenticatedHoSoCuaToiRouteImport.update({
  id: '/ho-so-cua-toi',
  path: '/ho-so-cua-toi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNopHoSoRoute = AuthenticatedNopHoSoRouteImport.update({
  id: '/nop-ho-so',
  path: '/nop-ho-so',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuanTriRoute = AuthenticatedQuanTriRouteImport.update({
  id: '/quan-tri',
  path: '/quan-tri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChienDichIndexRoute = ChienDichIndexRouteImport.update({
  id: '/chien-dich/',
  path: '/chien-dich/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChienDichSlugRoute = ChienDichSlugRouteImport.update({
  id: '/chien-dich/$slug',
  path: '/chien-dich/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DongGopSlugRoute = DongGopSlugRouteImport.update({
  id: '/dong-gop/$slug',
  path: '/dong-gop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bo-loc-xanh': typeof BoLocXanhRoute
  '/cong-tac-vien': typeof CongTacVienRoute
  '/doi-tac': typeof DoiTacRoute
  '/lien-he': typeof LienHeRoute
  '/ho-so-cua-toi': typeof AuthenticatedHoSoCuaToiRoute
  '/nop-ho-so': typeof AuthenticatedNopHoSoRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/chien-dich/$slug': typeof ChienDichSlugRoute
  '/dong-gop/$slug': typeof DongGopSlugRoute
  '/chien-dich/': typeof ChienDichIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bo-loc-xanh': typeof BoLocXanhRoute
  '/cong-tac-vien': typeof CongTacVienRoute
  '/doi-tac': typeof DoiTacRoute
  '/lien-he': typeof LienHeRoute
  '/ho-so-cua-toi': typeof AuthenticatedHoSoCuaToiRoute
  '/nop-ho-so': typeof AuthenticatedNopHoSoRoute
  '/quan-tri': typeof AuthenticatedQuanTriRoute
  '/chien-dich/$slug': typeof ChienDichSlugRoute
  '/dong-gop/$slug': typeof DongGopSlugRoute
  '/chien-dich': typeof ChienDichIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bo-loc-xanh': typeof BoLocXanhRoute
  '/cong-tac-vien': typeof CongTacVienRoute
  '/doi-tac': typeof DoiTacRoute
  '/lien-he': typeof LienHeRoute
  '/_authenticated/ho-so-cua-toi': typeof AuthenticatedHoSoCuaToiRoute
  '/_authenticated/nop-ho-so': typeof AuthenticatedNopHoSoRoute
  '/_authenticated/quan-tri': typeof AuthenticatedQuanTriRoute
  '/chien-dich/$slug': typeof ChienDichSlugRoute
  '/dong-gop/$slug': typeof DongGopSlugRoute
  '/chien-dich/': typeof ChienDichIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bo-loc-xanh'
    | '/cong-tac-vien'
    | '/doi-tac'
    | '/lien-he'
    | '/ho-so-cua-toi'
    | '/nop-ho-so'
    | '/quan-tri'
    | '/chien-dich/$slug'
    | '/dong-gop/$slug'
    | '/chien-dich/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bo-loc-xanh'
    | '/cong-tac-vien'
    | '/doi-tac'
    | '/lien-he'
    | '/ho-so-cua-toi'
    | '/nop-ho-so'
    | '/quan-tri'
    | '/chien-dich/$slug'
    | '/dong-gop/$slug'
    | '/chien-dich'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bo-loc-xanh'
    | '/cong-tac-vien'
    | '/doi-tac'
    | '/lien-he'
    | '/_authenticated/ho-so-cua-toi'
    | '/_authenticated/nop-ho-so'
    | '/_authenticated/quan-tri'
    | '/chien-dich/$slug'
    | '/dong-gop/$slug'
    | '/chien-dich/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoLocXanhRoute: typeof BoLocXanhRoute
  CongTacVienRoute: typeof CongTacVienRoute
  DoiTacRoute: typeof DoiTacRoute
  LienHeRoute: typeof LienHeRoute
  ChienDichSlugRoute: typeof ChienDichSlugRoute
  DongGopSlugRoute: typeof DongGopSlugRoute
  ChienDichIndexRoute: typeof ChienDichIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bo-loc-xanh': {
      id: '/bo-loc-xanh'
      path: '/bo-loc-xanh'
      fullPath: '/bo-loc-xanh'
      preLoaderRoute: typeof BoLocXanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-tac-vien': {
      id: '/cong-tac-vien'
      path: '/cong-tac-vien'
      fullPath: '/cong-tac-vien'
      preLoaderRoute: typeof CongTacVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doi-tac': {
      id: '/doi-tac'
      path: '/doi-tac'
      fullPath: '/doi-tac'
      preLoaderRoute: typeof DoiTacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ho-so-cua-toi': {
      id: '/_authenticated/ho-so-cua-toi'
      path: '/ho-so-cua-toi'
      fullPath: '/ho-so-cua-toi'
      preLoaderRoute: typeof AuthenticatedHoSoCuaToiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nop-ho-so': {
      id: '/_authenticated/nop-ho-so'
      path: '/nop-ho-so'
      fullPath: '/nop-ho-so'
      preLoaderRoute: typeof AuthenticatedNopHoSoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quan-tri': {
      id: '/_authenticated/quan-tri'
      path: '/quan-tri'
      fullPath: '/quan-tri'
      preLoaderRoute: typeof AuthenticatedQuanTriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/chien-dich/': {
      id: '/chien-dich/'
      path: '/chien-dich'
      fullPath: '/chien-dich/'
      preLoaderRoute: typeof ChienDichIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chien-dich/$slug': {
      id: '/chien-dich/$slug'
      path: '/chien-dich/$slug'
      fullPath: '/chien-dich/$slug'
      preLoaderRoute: typeof ChienDichSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dong-gop/$slug': {
      id: '/dong-gop/$slug'
      path: '/dong-gop/$slug'
      fullPath: '/dong-gop/$slug'
      preLoaderRoute: typeof DongGopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHoSoCuaToiRoute: typeof AuthenticatedHoSoCuaToiRoute
  AuthenticatedNopHoSoRoute: typeof AuthenticatedNopHoSoRoute
  AuthenticatedQuanTriRoute: typeof AuthenticatedQuanTriRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHoSoCuaToiRoute: AuthenticatedHoSoCuaToiRoute,
  AuthenticatedNopHoSoRoute: AuthenticatedNopHoSoRoute,
  AuthenticatedQuanTriRoute: AuthenticatedQuanTriRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BoLocXanhRoute: BoLocXanhRoute,
  CongTacVienRoute: CongTacVienRoute,
  DoiTacRoute: DoiTacRoute,
  LienHeRoute: LienHeRoute,
  ChienDichSlugRoute: ChienDichSlugRoute,
  DongGopSlugRoute: DongGopSlugRoute,
  ChienDichIndexRoute: ChienDichIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
